************* Module Factor_Models
python-scripts\Factor_Models.py:302:0: C0305: Trailing newlines (trailing-newlines)
python-scripts\Factor_Models.py:1:0: C0114: Missing module docstring (missing-module-docstring)
python-scripts\Factor_Models.py:1:0: C0103: Module name "Factor_Models" doesn't conform to snake_case naming style (invalid-name)
python-scripts\Factor_Models.py:40:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:42:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:73:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:74:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:74:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:76:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:89:0: C0413: Import "import matplotlib.pyplot as plt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:90:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:90:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:91:0: C0413: Import "from gs_quant.timeseries import beta" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:92:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:92:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:94:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:113:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:113:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:114:0: C0413: Import "import pandas as pd" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:115:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:115:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:117:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:123:0: C0103: Constant name "max_rows" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:124:0: C0103: Constant name "max_columns" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:142:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:142:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:143:0: C0413: Import "import matplotlib.ticker as mtick" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:144:0: C0413: Import "import numpy as np" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:145:0: W0404: Reimport 'matplotlib.pyplot' (imported line 89) (reimported)
python-scripts\Factor_Models.py:145:0: C0413: Import "import matplotlib.pyplot as plt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:146:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:146:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:148:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:192:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:192:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:193:0: W0404: Reimport 'pandas' (imported line 114) (reimported)
python-scripts\Factor_Models.py:193:0: C0413: Import "import pandas as pd" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:194:0: C0413: Import "from gs_quant.models.risk_model import RiskModelUniverseIdentifierRequest as Identifier, DataAssetsRequest" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:195:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:195:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:198:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:205:0: C0103: Constant name "max_rows" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:207:0: W0104: Statement seems to have no effect (pointless-statement)
python-scripts\Factor_Models.py:216:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:216:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:217:0: W0404: Reimport 'matplotlib.pyplot' (imported line 89) (reimported)
python-scripts\Factor_Models.py:217:0: C0413: Import "import matplotlib.pyplot as plt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:218:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:218:0: W0404: Reimport 'DataAssetsRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:218:0: W0404: Reimport 'RiskModelUniverseIdentifierRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:218:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel, DataAssetsRequest, RiskModelUniverseIdentifierRequest as Identifier" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:220:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:223:0: C0103: Constant name "asset_bbid" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:245:0: C0413: Import "import seaborn as sns" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:246:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:246:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:247:0: W0404: Reimport 'matplotlib.pyplot' (imported line 89) (reimported)
python-scripts\Factor_Models.py:247:0: C0413: Import "import matplotlib.pyplot as plt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:249:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:249:0: W0404: Reimport 'DataAssetsRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:249:0: W0404: Reimport 'RiskModelUniverseIdentifierRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:249:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel, DataAssetsRequest, RiskModelUniverseIdentifierRequest as Identifier" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:251:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:254:0: C0103: Constant name "asset_bbid" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:273:0: W0404: Reimport 'datetime' (imported line 73) (reimported)
python-scripts\Factor_Models.py:273:0: C0413: Import "import datetime as dt" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:274:0: W0404: Reimport 'FactorRiskModel' (imported line 40) (reimported)
python-scripts\Factor_Models.py:274:0: W0404: Reimport 'DataAssetsRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:274:0: W0404: Reimport 'RiskModelUniverseIdentifierRequest' (imported line 194) (reimported)
python-scripts\Factor_Models.py:274:0: C0413: Import "from gs_quant.models.risk_model import FactorRiskModel, Measure, DataAssetsRequest, RiskModelUniverseIdentifierRequest as Identifier" should be placed at the top of the module (wrong-import-position)
python-scripts\Factor_Models.py:276:0: C0103: Constant name "model_id" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:283:0: C0103: Constant name "asset_bbid" doesn't conform to UPPER_CASE naming style (invalid-name)
python-scripts\Factor_Models.py:73:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:90:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:113:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:142:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:192:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:216:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:246:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:273:0: C0411: standard import "import datetime as dt" should be placed before "from gs_quant.session import Environment, GsSession" (wrong-import-order)
python-scripts\Factor_Models.py:91:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:115:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:143:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:145:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:146:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:193:0: C0412: Imports from package pandas are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:194:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:217:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:218:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:247:0: C0412: Imports from package matplotlib are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:249:0: C0412: Imports from package gs_quant are not grouped (ungrouped-imports)
python-scripts\Factor_Models.py:144:0: W0611: Unused numpy imported as np (unused-import)

------------------------------------------------------------------
Your code has been rated at 2.76/10 (previous run: 2.76/10, +0.00)

